---
- hosts: web-servers
  user: ubuntu 
  sudo: True

  vars:
     max_children : "5" 
     start_servers : "2" 
     min_spare_servers: "2" 
     max_spare_servers: "2"

  tasks: 
     - include: tasks/setup.yml

  handlers: 
     - include: handlers/handler.yml

