--- 
## these are nginx inclue task
- name: install python-software-properties
  action: apt name='python-software-properties' state=installed

- name: "add nginx ppa if it ubuntu 10.04 and up"
  action: command add-apt-repository  -y ppa:nginx/stable
  only_if: "$is_ubuntu and $is_10_up"

- name: update apt repo
  action: command /usr/bin/apt-get update

- name: install nginx 
  action: apt name=nginx state=installed

- name:  copy fixed init for nginx
  action: copy src=nginx/files/nginx.init dest=/etc/init.d/nginx mode=0755 

- name: service nginx 
  action: service name=nginx state=started 

- name: write nginx.conf 
  action: template src='nginx/templates/nginx.conf.j2' dest='/etc/nginx/nginx.conf'
  notify:
    - restart nginx
