---      
   - name: install php-fpm 
     action: apt pkg=php5-fpm ensure=installed    

   - name: php install needed modules
     action: apt pkg=$item ensure=installed    
     with_items: 
        - php5-common
        - php5-curl
        - php5-gd
        - php5-mysql

   - name: service run php5-fpm 
     action: service name=php5-fpm state=started 

   - name: fpm config
     action: template src='php-fpm/templates/www.conf' dest='/etc/php5/fpm/pool.d/www.conf'
     notify: 
       - restart php5-fpm
